version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/app  # Mountet das dist-Verzeichnis aus WSL in den Container
    ports:
      - "3110:80"  # Mappt den Container-Port 8080 auf den Host-Port 8080

